# .github/workflows/terraform-apply.yml
name: "Terraform Apply"

on:
  push:
    branches:
      - main
    paths:
      - "**.tf"
      - "**.py"
      - ".github/workflows/terraform-apply.yml"

jobs:
  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="email_address=${{ secrets.EMAIL_ADDRESS }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="email_address=${{ secrets.EMAIL_ADDRESS }}"

      - name: Output API Gateway URL
        run: |
          echo "🐢 Apapp alert system deployed!"
          terraform output -raw qr_code_url
          echo ""
          echo "Use this URL to generate your QR codes."
